### ISSUE TITLE
Wildfly containers don't shutdown properly on Mac OSX

### ISSUE THREAD

**Issue by jkasztur** [jboss-qa/jcontainer-manager#128]
After wildfly container shuts down, I still have bash process running which consumes ~50% cpu. It happens only with wildfly.

**Comment by llowinge** [comment]
The same with my macbook...

**Comment by llowinge** [comment]
A believe there is some deadlock in https://github.com/jboss-qa/jcontainer-manager/blob/develop/core/src/main/java/org/jboss/qa/jcontainer/util/executor/ProcessExecutor.java#L159 and it doesn't read streams properly - then it stucks in https://github.com/jboss-qa/jcontainer-manager/blob/develop/core/src/main/java/org/jboss/qa/jcontainer/AbstractContainer.java#L139

**Comment by llowinge** [comment]
It can be reproduced with ```mvn clean install exec:java -Dexec.arguments=eap -DuseAlias -Djob.eap.url="file:/Users/llowinge/Redhat/xpaas/xpaas-qe/test-fuse/testovaci-hihi/wildfly-dist-7.1.2.GA-redhat-1.zip" -Djob.eap.fuse.installer.url="file:/Users/llowinge/Redhat/xpaas/xpaas-qe/test-fuse/testovaci-hihi/fuse-eap-installer-7.2.0.fuse-720014.jar" -Dworkspace=/Users/llowinge/Redhat/xpaas/xpaas-qe/test-fuse/testovaci-hihi/workspace```

and the output is: ```2018-11-01 11:42:15 WARN  AbstractContainer:181 - Container shutdown process didn't finish in 1 MINUTES!```
